import "dotenv/config"; 
import express from "express";
 import cors from "cors";
  import { connectDB } from "./config/db.js";
import auth from "./routes/authRoutes.js";
 import solar from "./routes/solarRoutes.js"; 
 import products from "./routes/productRoutes.js"; 
 import orders from "./routes/orderRoutes.js"; 
 import services from "./routes/serviceRoutes.js";
  import loans from "./routes/loanRoutes.js"; 
  import credits from "./routes/creditRoutes.js"; 
  import referrals from "./routes/referralRoutes.js"; 
  import payments from "./routes/paymentRoutes.js";
   import notifications from "./routes/notificationRoutes.js";
    import subsidies from "./routes/subsidyRoutes.js";
     import support from "./routes/supportRoutes.js";
      import admin from "./routes/adminRoutes.js";
const app=express(),PORT=process.env.PORT||5000; 
app.use(cors({origin:process.env.CLIENT_URL||"http://localhost:5173"}));
 app.use(express.json());
  app.get("/",(q,s)=>s.json({name:"SolarConnect API",status:"running"}));
  app.get("/api/health",(q,s)=>s.json({status:"ok",timestamp:new Date().toISOString()}));
   app.use("/api/auth",auth); 
   app.use("/api/solar",solar); 
   app.use("/api/products",products);
    app.use("/api/orders",orders);
     app.use("/api/services",services); 
     app.use("/api/loans",loans);
      app.use("/api/credits",credits);
       app.use("/api/referrals",referrals);
        app.use("/api/payments",payments);
         app.use("/api/notifications",notifications);
          app.use("/api/subsidies",subsidies);
           app.use("/api/support",support); 
           app.use("/api/admin",admin); 
           app.use((q,s)=>s.status(404).json({message:"API route not found"}));
            app.use((e,q,s,n)=>{console.error(e);
                s.status(e.status||500).json({message:e.message||"Server error"})});
                 connectDB().then(()=>app.listen(PORT,()=>console.log(`SolarConnect API running on http://localhost:${PORT}`))).catch(e=>{console.error("Database connection failed:",e.message);process.exit(1)});
